"""deleted bio field

Revision ID: 5dd2bf877852
Revises: 1313c91a3fc1
Create Date: 2025-04-05 14:56:43.671415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dd2bf877852'
down_revision = '1313c91a3fc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('bio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
