"""Remove direct user fields and add user relationship

Revision ID: 991c24c08e90
Revises: 5dd2bf877852
Create Date: 2025-04-16 12:09:30.311030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '991c24c08e90'
down_revision = '5dd2bf877852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buyer_listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('buyer_name')
        batch_op.drop_column('buyer_email')
        batch_op.drop_column('buyer_phone')

    with op.batch_alter_table('seller_listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('seller_name')
        batch_op.drop_column('seller_email')
        batch_op.drop_column('seller_phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller_listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('seller_email', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('seller_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('buyer_listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buyer_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('buyer_email', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('buyer_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
